name: "ai-pr-reviewer"

services:
    db:
        image: postgres:15-alpine
        env_file:
            - ../.env.local
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
          - ai_pr_reviewer_network
    app:
      build:
        context: ../
        dockerfile: Dockerfile.local
      env_file:
        - ../.env.local
      command: ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
      volumes:
        - ../:/app
      ports:
        - 8000:8000     
      depends_on:
        - db
        - redis
      networks:
        - ai_pr_reviewer_network
    redis:
        image: redis:7-alpine
        env_file:
            - ../.env.local
        ports:
            - 6379:6379
        volumes:
            - redis_data:/data
        networks:
          - ai_pr_reviewer_network


volumes:
    postgres_data: 
    redis_data:

networks:
  ai_pr_reviewer_network:
    driver: bridge